
[workspace]
members = [
  "nasl-builtin-core",
  "nasl-builtin-utils",
  "nasl-syntax",
  "nasl-interpreter",
  "nasl-cli",
  "storage",
  "redis-storage",
  "json-storage",
  "feed",
  "feed-verifier",
  "scanner-api",
  "models",
]
